USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE SANDBOX_DEVELOPER;
GRANT ROLE SANDBOX_DEVELOPER TO ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE SANDBOX_DB;
GRANT OWNERSHIP ON DATABASE SANDBOX_DB TO ROLE SANDBOX_DEVELOPER;

CREATE OR REPLACE WAREHOUSE SANDBOX_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE SANDBOX_WH TO ROLE SANDBOX_DEVELOPER;

CREATE OR REPLACE SCHEMA DEV;
GRANT OWNERSHIP ON SCHEMA DEV TO ROLE SANDBOX_DEVELOPER;

CREATE OR REPLACE SCHEMA TEST;
GRANT OWNERSHIP ON SCHEMA TEST TO ROLE SANDBOX_DEVELOPER;
